apiVersion : apps/v1
kind: Deployment
metadata:
  name: sample-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-react-app
  template:
    metadata:
      labels:
        app: sample-react-app
    spec:
      containers:
        - name: sample-react-app
          image: lwfecr.azurecr.io/sample-react-app
          ports:
          - containerPort: 80