apiVersion : apps/v1
kind: Deployment
metadata:
  name: sample-react-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-react-app
    selector:
      matchLabels:
        app: sample-react-app

    spec:
      containers:
        - name: sample-react-app
          image: lwfecr.azurecr.io/sample-react-repo
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: sample-react-app
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: sample-react-app